In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.2'

##### Points to notify


- array operations
- multidimentional aggregations
- aggregation functions

##### Aggregations: Min, Max, and Everything in Between

Often when you are faced with a large amount of data, a first step is to compute sum‐
mary statistics for the data in question. Perhaps the most common summary statistics
are the mean and standard deviation, which allow you to summarize the “typical” val‐
ues in a dataset, but other aggregates are useful as well (the sum, product, median,
minimum and maximum, quantiles, etc.).

NumPy has fast built-in aggregation functions for working on arrays; we’ll discuss
and demonstrate some of them here.

###### Summing the Values in an Array

In [3]:
L = np.random.random(100)
np.sum(L)

49.98675897615992

###### Minimum and Maximum

In [6]:
np.min(L)
L.min()

0.002438591670151369

In [7]:
np.max(L)
L.max()

0.987449086971802

##### Multidimensional aggregates

In [8]:
M = np.random.random((3, 4))
print(M)

[[0.43112061 0.48390741 0.59099942 0.76012316]
 [0.47524237 0.69781638 0.62908905 0.327929  ]
 [0.66237814 0.89652001 0.21629226 0.04141508]]


In [10]:
M.sum()

6.212832884442788

The function returns four values, corresponding to the four columns of numbers.
Similarly, we can find the maximum value within each row:

In [11]:
M.min(axis=0)

array([0.43112061, 0.48390741, 0.21629226, 0.04141508])

In [12]:
M.max(axis=1)

array([0.76012316, 0.69781638, 0.89652001])

##### Other aggregation functions

NumPy provides many other aggregation functions, but we won’t discuss them in
detail here. Additionally, most aggregates have a NaN-safe counterpart that computes
the result while ignoring missing values,

In [14]:
x = np.arange(100)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [22]:
print("Sum is ", x.sum())
print("Product is ", x.prod())
print("Mean is ", x.mean())
print("Std is ", x.std())
print("Variance is ", x.var())
print("Min is ", x.min())
print("Max is ", x.max())
print("argmin is ", x.argmin())
print("argmax is ", x.argmax())
print("median is ", np.median(x))
print("percentile is ", np.percentile(x, 99))

Sum is  4950
Product is  0
Mean is  49.5
Std is  28.86607004772212
Variance is  833.25
Min is  0
Max is  99
argmin is  0
argmax is  99
median is  49.5
percentile is  98.01


##### NaN-safe Version

np.nansum <br>
np.nanprod <br>
np.nanmean <br>
np.nanstd <br>
np.nanvar <br>
np.nanmin <br>
np.nanmax <br>
np.nanargmin <br>
np.nanargmax <br>
np.nanmedian <br>
np.nanpercentile 

##### Example